set -g focus-events on

# explicitly state that outer terminal supports TrueColor
set -as terminal-overrides ",*-256color:Tc"
set -ga terminal-features ",xterm-256color:RGB"
set -as terminal-features ",*:osc-11"

set -g base-index 1          # windows start at 1
set -g pane-base-index 1     # panes start at 1
set -g renumber-windows on   # re-number windows when one is closed

bind s choose-tree -Zs -O name

# for convenience
set -g mouse on
set -g set-clipboard on

# for agents
set -g monitor-bell on
set -g allow-passthrough on  # for OSC;9 (notifs)

# needed for shift+enter (claude code, codex, etc)
bind-key -n S-Enter send-keys Escape "[13;2u"
set -s extended-keys on
set -as terminal-features 'tmux-256color:extkeys'

# per-pane highlighted titlebar; makes it more clear which pane is active

# only show per-pane status when >1 pane exists
set-hook -g after-split-window   "if -F '#{>:#{window_panes},1}' 'set pane-border-status top' 'set pane-border-status off'"
set-hook -g pane-exited          "if -F '#{>:#{window_panes},1}' 'set pane-border-status top' 'set pane-border-status off'"
set-hook -g window-layout-changed "if -F '#{>:#{window_panes},1}' 'set pane-border-status top' 'set pane-border-status off'"
# set -g pane-border-status top
set -g pane-border-status off   # start hidden; hooks will enable when needed
set -g pane-border-format " #{pane_index} "
set -g pane-border-style 'fg=colour250'
set -g pane-active-border-style 'fg=colour205,bold'
set -g pane-border-format " #[bold]#{?pane_active,#[bg=colour205]#[fg=colour255] ● #{pane_current_command} #[default],○ #{pane_current_command}} "

# -- misc decent 256color highlight opts --
# colour203: #E06C75 (Coral rose)
# colour221: #E5C07B (Amber gold)
# colour176: #C678DD (Lavender)
# colour114: #98C379 (Sage green)
# colour75: #61AFEF (Sky blue)
# colour173: #D19A66 (Burnt orange)
# colour39: #00AFFF (Cyan (current))
# colour205: #FF6EB4 (Hot pink)

unbind l
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5
